### ISSUE TITLE
Syntax error or access violation

### ISSUE THREAD

**Issue by edward-jw-yu** [walkor/mysql#20]
**Mysql version is 5.7.33**

**When I called the following:** 
`$results = self::$mysql->select('*')->from('products')->where('key= :key')->bindValues(array('key' => $msg->pid))->query();`
**It came out the following error:** 
PDOException: SQL:SELECT * FROM `products` WHERE key=:key SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key=?' at line 1 in vendor/workerman/mysql/src/Connection.php:1770.

**When I called the following:** 
`$results = self::$mysql->select('*')->from('products')->query();`
It worked well.

**Comment by walkor** [comment]
Maybe it's because key is a keyword.
Try
```php
->where('`key`= :key')
```

**Comment by edward-jw-yu** [comment]
Thanks a lot.  It works~
