### ISSUE TITLE
提BUG

### ISSUE THREAD

**Issue by wangjiazheng** [walkor/mysql#4]
https://github.com/walkor/mysql/blob/ffac39353f247a61c89af4b3e812f3bcbb4fd09c/src/Connection.php#L533

此处需要考虑，如果 ->select( "a, b, c") 时，那么会被重新组装成 a, AS b, AS c 而出错。
我没法提交，麻烦作者提交一下。
533行这一句，改为：
if ($count == 2 && trim($parts[0]) != '' && trim($parts[1]) != '') {

538行这一句，改为：
$this->cols[] = trim($spec);

由于这一段时间，我没有composer update，就没有发现这个问题。昨天我更新了之后，今天发现了因此发生的一些问题。我相信也有其他小伙伴会遇到同样的问题。麻烦有时间修改一下，谢谢！

**Comment by walkor** [comment]
fixed

**Comment by walkor** [comment]
thanks
