### ISSUE TITLE
mysql服务重新启动后pdo值为null的问题

### ISSUE THREAD

**Issue by eaglexpf** [walkor/mysql#6]
我发现；当mysql服务暂时无法通信时；重连机制会使pdo的值为null；这样即使mysql服务恢复通信后，代码也依然会有"Call to a member function prepare() on null"的错误；

是否可以在第1736行前加上一个判断pdo是否为空的判断

`if (is_null($this->pdo)){
                $this->connect();
            }`

或者有其他更好的方式吗

**Comment by walkor** [comment]
感谢反馈
